---
# additional control to be overwritten
output_root_dir: output_adaptive
global:
  batch_size:
    train: 250
    test: 250
  shuffle:
    train: true
    test: false
  num_epochs: 800
  optimizer_name: Adam
  betas: [0.9, 0.99]
  lr: 0.001
  weight_decay: 0
  scheduler_name: CosineAnnealingLR
